***NUMPY***

In [2]:
import numpy as np

sample=np.array([10,30,4,20,78,89,65])

In [5]:
print(sample.ndim)
print(sample.shape)
print(sample.size)
print(sample.dtype)

1
(7,)
7
int64


In [9]:
marks = np.array([75, 82, 91, 68, 88])

print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

404
80.8
91
68


In [10]:
students = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 90, 92]
])

In [18]:
print(students.shape)
print(students[0,:])
print(students[1,1])
print(students[:,0])
print(np.mean(students))

(3, 3)
[80 70 90]
85
[80 60 95]
81.88888888888889


***condition***

Numbers greater than 50


Numbers less than 50



Numbers between 30 and 80


Numbers greater than or equal to 70

In [19]:
numbers = np.array([10, 25, 40, 55, 70, 85, 100])

In [34]:

print(numbers[numbers > 50])
print(numbers[numbers < 50])
print(numbers[(numbers>30)&(numbers<80)])
print(numbers[numbers>=70])

[ 55  70  85 100]
[10 25 40]
[40 55 70]
[ 70  85 100]


Highest 3 marks using slicing after sorting


Marks above 60

Marks below 50

Marks between 50 and 80


In [35]:
marks = np.array([45, 67, 89, 32, 95, 72, 50])

In [38]:
mark=np.sort(marks)
print(mark)

[32 45 50 67 72 89 95]


In [45]:
print(mark[-1:-4:-1])
print(numbers[numbers > 60])
print(numbers[numbers < 50])
print(numbers[(numbers>50)&(numbers<80)])

[95 89 72]
[ 70  85 100]
[10 25 40]
[55 70]


All student IDs

All marks

Students who scored ≥ 60

Students who scored < 50

Students who scored between 60 and 90

In [46]:
students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 35],
    [105, 78],
    [106, 60]
])

In [50]:
print(students[:,0])
print(students[:,0])
print(numbers[numbers >= 60])
print(numbers[numbers < 50])
print(numbers[(numbers>60)&(numbers<90)])

[101 102 103 104 105 106]
[101 102 103 104 105 106]
[ 70  85 100]
[10 25 40]
[70 85]


***NumPy Broadcasting & Vectorization***

broadcasting

In [1]:
import numpy as np

data=np.array([10,20,30,40,50,60,70,80,90,100])

print(data +5)

[ 15  25  35  45  55  65  75  85  95 105]


Broadcasting with 2D Arrays

In [2]:
data1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(data1 *2)

[[ 20  40  60]
 [ 80 100 120]]


In [3]:
data2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

values = np.array([1, 2, 3])

print(data2 + values)

[[11 22 33]
 [41 52 63]]


Row-wise Calculation

In [4]:
scores = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 90, 92]
])

bonus = np.array([5, 3, 2])

print(scores + bonus)

[[ 85  73  92]
 [ 65  88  77]
 [100  93  94]]


Column-wise Broadcasting

In [5]:
data = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])

adjustment = np.array([[1],[2],[3]])

print(data + adjustment)

[[ 11 101]
 [ 22 202]
 [ 33 303]]


reshape()

(row,colunm)

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6])

matrix = numbers.reshape(2, 3)

print(matrix)

[[1 2 3]
 [4 5 6]]


axis

In [9]:
marks = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 90, 92]
])
print(np.mean(marks, axis=1))
print(np.mean(marks, axis=0))



[80.         73.33333333 92.33333333]
[78.33333333 81.66666667 85.66666667]


Normalization

In [12]:
data=np.array([10,34,56,7,87,64,53,55,24])

n_values=data/np.max(data)
print(n_values)

[0.11494253 0.3908046  0.64367816 0.08045977 1.         0.73563218
 0.6091954  0.63218391 0.27586207]


Standardization

z = (x - mean) / standard deviation

In [13]:
standardized_data = (data - np.mean(data)) / np.std(data)

print(standardized_data)

[-1.33440128 -0.37363236  0.50707249 -1.4544974   1.74806568  0.82732879
  0.38697637  0.46704045 -0.77395274]
