***NUMPY***

In [2]:
import numpy as np

sample=np.array([10,30,4,20,78,89,65])

In [5]:
print(sample.ndim)
print(sample.shape)
print(sample.size)
print(sample.dtype)

1
(7,)
7
int64


In [9]:
marks = np.array([75, 82, 91, 68, 88])

print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

404
80.8
91
68


In [10]:
students = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 90, 92]
])

In [18]:
print(students.shape)
print(students[0,:])
print(students[1,1])
print(students[:,0])
print(np.mean(students))

(3, 3)
[80 70 90]
85
[80 60 95]
81.88888888888889


***condition***

Numbers greater than 50


Numbers less than 50



Numbers between 30 and 80


Numbers greater than or equal to 70

In [19]:
numbers = np.array([10, 25, 40, 55, 70, 85, 100])

In [34]:

print(numbers[numbers > 50])
print(numbers[numbers < 50])
print(numbers[(numbers>30)&(numbers<80)])
print(numbers[numbers>=70])

[ 55  70  85 100]
[10 25 40]
[40 55 70]
[ 70  85 100]


Highest 3 marks using slicing after sorting


Marks above 60

Marks below 50

Marks between 50 and 80


In [35]:
marks = np.array([45, 67, 89, 32, 95, 72, 50])

In [38]:
mark=np.sort(marks)
print(mark)

[32 45 50 67 72 89 95]


In [45]:
print(mark[-1:-4:-1])
print(numbers[numbers > 60])
print(numbers[numbers < 50])
print(numbers[(numbers>50)&(numbers<80)])

[95 89 72]
[ 70  85 100]
[10 25 40]
[55 70]


All student IDs

All marks

Students who scored ≥ 60

Students who scored < 50

Students who scored between 60 and 90

In [46]:
students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 35],
    [105, 78],
    [106, 60]
])

In [50]:
print(students[:,0])
print(students[:,0])
print(numbers[numbers >= 60])
print(numbers[numbers < 50])
print(numbers[(numbers>60)&(numbers<90)])

[101 102 103 104 105 106]
[101 102 103 104 105 106]
[ 70  85 100]
[10 25 40]
[70 85]
